# Generated by Django 5.2.4 on 2025-07-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdredAt', models.DateTimeField(auto_now_add=True)),
                ('TotalItems', models.IntegerField(default=0)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Order', models.JSONField()),
                ('OrderStatus', models.CharField(choices=[('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('in_process', 'In Process')], default='in_process', max_length=20)),
            ],
        ),
    ]
