# Generated by Django 5.2.4 on 2025-07-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_orderslist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderslist',
            old_name='OrdredAt',
            new_name='OrderedAt',
        ),
    ]
